config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  validates :birth_date, presence: true
  validates :color, presence: true, inclusion: { in: %w(black white tuxedo calico tabby)}
  validates :name, presence: true
  validates :sex, presence: true, inclusion: { in: %w(M F)}
  validates :description, presence: true
  has_many :cat_rental_requests
  # start_date: 10/31/2017
  # end_date: 1/05/2017
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  belongs_to :cat, dependent: :destroy
  validate :does_not_overlap_approved_request

  def overlapping_requests

    CatRentalRequest
    .where.not(id: self.id)
    .where(cat_id: self.cat_id)
    .where.not('start_date > ? OR end_date < ?', end_date, start_date)

  end

  def overlapping_approved_request
    overlapping_requests.where("status = 'APPROVED'")
  end

  def does_not_overlap_approved_request
    overlapping_approved_request.exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
    byebug
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cats_url
    else
      render :new
    end
  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cats_url(@cat)
    else
      render :edit
    end
  end



  private
  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :description, :birth_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<form class="" action="<%=cat_rental_requests_url%>" method="post">
  <label for="cat-names">Name</label>
  <select id="cat-names"name="cat">
    <% cats.each do |cat| %>
    <option value="cat_rental_request[<%=cat.name%>]"><%=cat.name%></option>
    <% end %>
  </select>
  <label for="start-date">Start Date:</label>
  <input id="start-date" type="date" name="cat_rental_request[start_date]" value="">
  <label for="end-date">End Date:</label>
  <input id="end-date" type="date" name="cat_rental_request[end_date]" value="">

  <input type="submit" name="" value="Request Cat">
</form>

app/views/cat_rental_requests/new.html.erb
<h1>Request Cat</h1>

<%= render 'form', cats: @cats, action: :create %>

app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_url = edit_cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>


<form action="<%=action_url%>" method="post">
  <% if action == :edit %>
  <input type="hidden" value="_method" method="patch"></input>
  <% end %>

  <label for="name">Name</label>
  <input id='name' type="text" name="cat[name]" value="<%=cat.name%>">

  <label for="">Sex
    <label for="M">M</label>
    <input id='M' type="radio" name="cat[sex]" value="M" <%= action == :edit && cat.sex == 'M' ? "checked" : "" %>>
    <label for="F">F</label>
    <input id='F' type="radio" name="cat[sex]" value="F" <%= action == :edit && cat.sex == 'F' ? "checked" : "" %>>
  </label>


  <label for="birth_date">Birth Date</label>
  <input id='birth_date' type="date" name="cat[birth_date]" value="<%=cat.birth_date%>">

  <label for="color">Color</label>


  <select id="color" name="cat[color]">
    <option <%= action == :edit ? "" : "selected" %> disabled>Choose your cat color</option>
    <option <%= action == :edit && cat.color == 'black' ? "selected" : "" %> value="black">black</option>
    <option <%= action == :edit && cat.color == 'white' ? "selected" : "" %> value="white">white</option>
    <option <%= action == :edit && cat.color == 'calico' ? "selected" : "" %> value="calico">calico</option>
    <option <%= action == :edit && cat.color == 'tuxedo' ? "selected" : "" %> value="tuxedo">tuxedo</option>
    <option <%= action == :edit && cat.color == 'tabby' ? "selected" : "" %> value="tabby">tabby</option>
  </select>

  <label for="description">Description</label>
  <textarea id='description' name="cat[description]" rows="8" cols="80">
    <%=cat.description%>
  </textarea>

  <input type="submit" value="<%= action == :edit ? "update cat" : "create new cat" %>">
</form>

app/views/cats/edit.html.erb
<h1>Edit Cat!</h1>


<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>Here are all the cats!</h1>

<ul>
  <% @cats.each do |cat| %>
  <li><a href="<%=cat_url(cat)%>"><%= cat.name %></a></li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h1>Make a new cat!</h1>

<%= render 'form', cat: @cat, action: :create %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Birth Date</th>
    <th>Description</th>
  </tr>
  <tr>
    <td> <%= @cat.name %> </td>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.sex %> </td>
    <td> <%= @cat.birth_date %> </td>
    <td> <%= @cat.description %> </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>